import Head from "next/head";
import { useSelector } from "react-redux";
import styles from "../styles/Home.module.css";

export default function Home() {
  const user = useSelector((state) => state?.user) || {};
  const Products = useSelector((state) => state?.products) || {};

  console.log(Products.allProducts.data.data);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <ul>
            {Products &&
              Products.allProducts.data.data.map((el, i) => (
                <li key={i}>{el.name}</li>
              ))}
          </ul>

          <ul>
            {user &&
              user.info.map((el, i) => <li key={i}>{el.mission_name}</li>)}
          </ul>
          <div></div>
        </div>

        <div className={styles.center}>
          <div className={styles.thirteen}></div>
        </div>

        <div className={styles.grid}></div>
      </main>
    </>
  );
}
